In [1]:
import numpy as np

In [9]:
# randomly initializing numpy arrays

narr1 = np.random.randint(1,10,(3,2))
narr2 = np.random.randint(1,10,(2,3))

print(narr1)
print(narr2)

[[3 2]
 [3 7]
 [6 7]]
[[7 4 1]
 [1 9 6]]


In [10]:
# matrix multiplication

mul = np.dot(narr1,narr2)
print(mul)


[[23 30 15]
 [28 75 45]
 [49 87 48]]


In [19]:
# mean of first matrix

mean = np.mean(narr1)
print(mean)

4.666666666666667


In [69]:
import pandas as pd

mtcars = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')

narr = np.array(mtcars.iloc[:,1:]) # leaving first column

# finding mean centered version by column
nparrayCentered = narr.T - np.mean(narr, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print(nparrayCentered)


[[-8.90727273e+00 -2.39072727e+01  1.30092727e+02  8.00927273e+01
  -2.60072727e+01 -2.72872727e+01 -1.34472727e+01 -2.99072727e+01
  -2.89072727e+01 -2.59072727e+01 -2.59072727e+01]
 [-8.98136364e+00 -2.39813636e+01  1.30018636e+02  8.00186364e+01
  -2.60813636e+01 -2.71063636e+01 -1.29613636e+01 -2.99813636e+01
  -2.89813636e+01 -2.59813636e+01 -2.59813636e+01]
 [-7.98181818e-01 -1.95981818e+01  8.44018182e+01  6.94018182e+01
  -1.97481818e+01 -2.12781818e+01 -4.98818182e+00 -2.25981818e+01
  -2.25981818e+01 -1.95981818e+01 -2.25981818e+01]
 [-1.73395455e+01 -3.27395455e+01  2.19260455e+02  7.12604545e+01
  -3.56595455e+01 -3.55245455e+01 -1.92995455e+01 -3.77395455e+01
  -3.87395455e+01 -3.57395455e+01 -3.77395455e+01]
 [-3.49645455e+01 -4.56645455e+01  3.06335455e+02  1.21335455e+02
  -5.05145455e+01 -5.02245455e+01 -3.66445455e+01 -5.36645455e+01
  -5.36645455e+01 -5.06645455e+01 -5.16645455e+01]
 [-1.69490909e+01 -2.90490909e+01  1.89950909e+02  6.99509091e+01
  -3.22890909e+01 -