In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [3]:
# Imports
import torch.nn as nn

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [6]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [7]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[91., 88., 64.],
         [91., 88., 64.],
         [69., 96., 70.],
         [69., 96., 70.],
         [73., 67., 43.]]), tensor([[ 81., 101.],
         [ 81., 101.],
         [103., 119.],
         [103., 119.],
         [ 56.,  70.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [9]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5389,  0.2047,  0.0765],
        [ 0.2905, -0.0629, -0.2140]], requires_grad=True)
Parameter containing:
tensor([ 0.3987, -0.5415], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [10]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)


### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [11]:
# Import nn.functional
import torch.nn.functional as F

In [12]:
# Define loss function
loss_fn = F.mse_loss

In [13]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4969.4346, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [17]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [18]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(44.1097, grad_fn=<MseLossBackward>)


In [19]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.9791,  72.1585],
        [ 80.5928,  97.5752],
        [119.9191, 138.0746],
        [ 30.5821,  47.0177],
        [ 93.6119, 107.7337],
        [ 58.9791,  72.1585],
        [ 80.5928,  97.5752],
        [119.9191, 138.0746],
        [ 30.5821,  47.0177],
        [ 93.6119, 107.7337],
        [ 58.9791,  72.1585],
        [ 80.5928,  97.5752],
        [119.9191, 138.0746],
        [ 30.5821,  47.0177],
        [ 93.6119, 107.7337]], grad_fn=<AddmmBackward>)

In [20]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [21]:
fit(100, model, loss_fn, opt)

Training loss:  tensor(15.7976, grad_fn=<MseLossBackward>)


#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 