In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')


In [31]:
X = tf.convert_to_tensor(inputs, dtype='float32')
Y = tf.convert_to_tensor(targets, dtype='float32')

W = tf.Variable(tf.ones([2, 3]), name="weight")

b = tf.Variable(tf.zeros([2]), name="bias")

In [34]:
# Define the model
def model(x):
    return x @ tf.transpose(W) + b

In [37]:
# Generate predictions
preds = model(inputs)

In [38]:
# Compare with targets
print("Predictions : ", preds)
print("Targets : ",targets)

Predictions :  tf.Tensor(
[[183. 183.]
 [243. 243.]
 [279. 279.]
 [182. 182.]
 [235. 235.]
 [183. 183.]
 [243. 243.]
 [279. 279.]
 [182. 182.]
 [235. 235.]
 [183. 183.]
 [243. 243.]
 [279. 279.]
 [182. 182.]
 [235. 235.]], shape=(15, 2), dtype=float32)
Targets :  [[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [41]:
def mse(y, pred):
    return tf.reduce_mean(tf.square(y - pred))

In [42]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tf.Tensor(19972.7, shape=(), dtype=float32)


In [55]:
# compute gradients
x_shape = inputs.shape

biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (tf.matmul(tf.transpose((preds-targets)),inputs))*2/x_shape[0]

print(weights_grad)
print(biases_grad)

tf.Tensor(
[[ 67.923775 -53.69639  -15.450201]
 [ 67.00281  -38.93234  -37.985188]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.2333547   0.12694295]
 [ 0.17021891 -0.1646698 ]
 [-0.18762308  0.13113403]
 [ 0.32686132  0.48244527]
 [-0.38985798 -0.47196656]
 [ 0.2333547   0.12694295]
 [ 0.17021891 -0.1646698 ]
 [-0.18762308  0.13113403]
 [ 0.32686132  0.48244527]
 [-0.38985798 -0.47196656]
 [ 0.2333547   0.12694295]
 [ 0.17021891 -0.1646698 ]
 [-0.18762308  0.13113403]
 [ 0.32686132  0.48244527]
 [-0.38985798 -0.47196656]], shape=(15, 2), dtype=float32)


In [49]:
# Adjust weights
W = W - weights_grad * 1e-5
b = b - biases_grad * 1e-5

print(W)
print(b)

tf.Tensor(
[[-0.01377591 -0.02011204  0.35569596]
 [ 0.093328    0.08796793  0.42560005]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.000508 -0.000452]
 [-0.000648 -0.000568]
 [-0.00064  -0.000584]
 [-0.00064  -0.00058 ]
 [-0.000528 -0.000464]
 [-0.000508 -0.000452]
 [-0.000648 -0.000568]
 [-0.00064  -0.000584]
 [-0.00064  -0.00058 ]
 [-0.000528 -0.000464]
 [-0.000508 -0.000452]
 [-0.000648 -0.000568]
 [-0.00064  -0.000584]
 [-0.00064  -0.00058 ]
 [-0.000528 -0.000464]], shape=(15, 2), dtype=float32)


In [50]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tf.Tensor(4097.9634, shape=(), dtype=float32)


In [56]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@tf.transpose(W))+b)-targets))*2/x_shape[0]
    weights_grad = (tf.matmul(tf.transpose((((inputs@tf.transpose(W))+b)-targets)),inputs))*2/x_shape[0]

    W -= weights_grad * 1e-5
    b -= biases_grad * 1e-5

In [57]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tf.Tensor(1.3712609, shape=(), dtype=float32)


In [58]:
# Print predictions
print(preds)
print(targets)

tf.Tensor(
[[ 57.235588  70.45233 ]
 [ 81.99816   99.81644 ]
 [119.052246 134.66989 ]
 [ 21.469795  37.75357 ]
 [101.33256  117.22136 ]
 [ 57.235588  70.45233 ]
 [ 81.99816   99.81644 ]
 [119.052246 134.66989 ]
 [ 21.469795  37.75357 ]
 [101.33256  117.22136 ]
 [ 57.235588  70.45233 ]
 [ 81.99816   99.81644 ]
 [119.052246 134.66989 ]
 [ 21.469795  37.75357 ]
 [101.33256  117.22136 ]], shape=(15, 2), dtype=float32)
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
