Task 1: Try the algo on Dataset2 - OneHotEncoding of features and Train test Division 75%-25%

In [18]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

data = pd.read_csv("PracticeDataSets/Dataset2.csv")
print(data)

   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [19]:
dummy_humidity = pd.get_dummies(data['Humidity'])
# print("\n\nDummy :\n",dummy)
data = data.drop(['Humidity'],axis=1)
data = pd.concat([dummy_humidity,data],axis=1)

dummy_wind = pd.get_dummies(data['Wind'])
# print("\n\nDummy :\n",dummy)
data = data.drop(['Wind'],axis=1)
data = pd.concat([dummy_wind,data],axis=1)
# print("\n\nFinal Data :\n",data)

dummy_temp = pd.get_dummies(data['Temp'])
# print("\n\nDummy :\n",dummy)
data = data.drop(['Temp'],axis=1)
data = pd.concat([dummy_temp,data],axis=1)
# print("\n\nFinal Data :\n",data)

dummy_outlook = pd.get_dummies(data['Outlook'])
# print("\n\nDummy :\n",dummy)
data = data.drop(['Outlook'],axis=1)
data = pd.concat([dummy_outlook,data],axis=1)
# print("\n\nFinal Data :\n",data)

print("\n\nFinal Data :\n",data)



Final Data :
     O  R  S  C  H  M  F  T  High  Low  Normal Class
0   0  1  0  0  1  0  1  0     0    0       1     N
1   0  1  0  0  1  0  0  1     1    0       0     N
2   1  0  0  0  1  0  1  0     0    0       1     Y
3   0  0  1  0  0  1  1  0     0    0       1     N
4   0  0  1  0  0  1  1  0     0    0       1     Y
5   0  0  1  0  0  1  0  1     0    1       0     Y
6   1  0  0  1  0  0  0  1     0    0       1     Y
7   0  1  0  1  0  0  1  0     0    0       1     Y
8   0  1  0  1  0  0  1  0     0    1       0     Y
9   0  0  1  0  0  1  1  0     1    0       0     Y
10  0  1  0  0  0  1  0  1     1    0       0     Y
11  1  0  0  0  0  1  0  1     0    1       0     Y
12  1  0  0  0  1  0  1  0     0    0       1     Y
13  0  0  1  0  0  1  0  1     0    0       1     N


In [20]:
X = data.iloc[:, :-1].values 

Y = data.iloc[:, -1].values 


print("\n\nData : \n", X) 
print("\n\nTarget: \n", Y) 



Data : 
 [[0 1 0 0 1 0 1 0 0 0 1]
 [0 1 0 0 1 0 0 1 1 0 0]
 [1 0 0 0 1 0 1 0 0 0 1]
 [0 0 1 0 0 1 1 0 0 0 1]
 [0 0 1 0 0 1 1 0 0 0 1]
 [0 0 1 0 0 1 0 1 0 1 0]
 [1 0 0 1 0 0 0 1 0 0 1]
 [0 1 0 1 0 0 1 0 0 0 1]
 [0 1 0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 0 1 1 0 0]
 [1 0 0 0 0 1 0 1 0 1 0]
 [1 0 0 0 1 0 1 0 0 0 1]
 [0 0 1 0 0 1 0 1 0 0 1]]


Target: 
 ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [21]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(X,Y, test_size = 0.25, random_state = 85)

In [22]:
import numpy as np
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [23]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.5


In [24]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 0],
       [2, 2]])

In [25]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 1.]
recall: [0.  0.5]


/home/priyavardhan/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
